### PR TITLE
Remove DolphinQt2

### PR DESCRIPTION
**Pull request by malleoz**
Dolphin Lua Core is based on Wx. The version of Dolphin we are based off of was in the transition phase going towards Qt, but it is not fully implemented. Thus, Wx must still be used for this version, meaning all Qt dependencies/references should be removed.

To review this PR: Check that there are no remaining references to Qt anywhere in source code.

### CODE REVIEW

**Review by ximk — DISMISSED** [review]
This looks good, if we missed something, it's not obvious.

**Comment by malleoz** [comment]
Found a couple files that were also unnecessary, but unsure about the following:

- \Tools\deploy-mac.py (is this even used? What is its purpose)

**Comment by malleoz** [comment]
This should be good now. The one uncertain file deploy-mac.py.... I've identified that it's still required for Mac building as it is directly referenced in the CMakeList.txt. So all I did was remove its references to Qt.

**It's currently untested so I'd like to get a Mac user to build this before I merge.**

**Comment by malleoz** [comment]
From hibyehello: "iirc that [file] packages up the binary for macs, but it isn't needed. cmake works just great for everything mac".

Thus, I'm okay with this being merged now.

**Review by vabold — APPROVED** [review]

**Pull request merged**
